config/routes.rb
Rails.application.routes.draw do
  
  get 'sharing/sendsms/' => 'sharing#sendsms', as: 'send_sms'
  post 'sharing/confirm_id' => 'sharing#confirm_id'

    

  get 'sharing/selection' => 'sharing#selection', as: 'select_univ'
  get 'sharing/selection2/:id' => 'sharing#selection2'
  get 'sharing/selection3/:id' => 'sharing#selection3'
  
  
  get 'sharing/reassure/:id' => 'sharing#reassure'
  get 'sharing/confirm_sms/:id' => 'sharing#confirm_sms'
  get 'sharing/reject_sms/:id' => 'sharing#reject_sms'
  

  get 'sharing/mymessages'
  get 'sharing/logout'
  
  root 'sharing#index'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
end

app/models/university.rb
class University < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/capch_controller.rb
class CapchController < ApplicationController
  def index
  end
end

app/controllers/sharing_controller.rb
class SharingController < ApplicationController
  before_action :check_session, except: [:index, :confirm_id, :reassure, :confirm_sms, :reject_sms]    
  require 'bitly'
  require 'savon'
  #isCheck = 2는 허락 함
  #isCheck = 1은 허락 안함
  #isCheck = 0은 확인 안함
    
    
  #번호를 공유한다고 했을때 자신의 번호를 요청한 사람에게 보내는 페이지.  
  def confirm_sms
    @post = Post.find(params[:id])
    if(@post.ischeck == 0)
      @post.ischeck = 2
      @post.save
      @receiver = User.find(@post.receiver_id)
      @sender = User.find(@post.user_id)
      lms_user = 'likelion'
      lms_password = 'likelion1111'
      
      msg = @receiver.name + "님의 번호는 " + @receiver.mobile + "입니다"
      title = "멋쟁이 사자입니다." ##문자 메시지
      
      h = Hash.new
      h["senderPhone"] = "010-3707-4919"
      h["receivePhone"] = @sender.mobile
      
      hash_value = Digest::MD5.hexdigest(lms_user + lms_password + h["receivePhone"])
      h["hashValue"] = hash_value
      h["lmsContent"] = msg
      h["lmsID"] = lms_user
      h["lmsTitle"] = title
      
      client = Savon.client(wsdl: "http://lmsservice.tongkni.co.kr/lms.1/ServiceLMS.asmx?WSDL")
      res = client.call :send_lms, :message => h
      puts res.inspect    
    end
  end
  
  #번호를 거절했을때 나타나는 페이지.
  def reject_sms
    @post = Post.find(params[:id])
    if(@post.ischeck == 0)
      @post.ischeck = 1
      @post.save
    end
    redirect_to '/'
  end
  
  #번호를 교환할건지 아닌지 물어보는 페이지.
  def reassure
    @post = Post.find(params[:id])
  end

  #자신이 보낸 메세지들을 확인하는 페이지  
  def mymessages
    @user = User.find(session[:user_id])
  end


  #index 맨 처음 페이지..
  def index
    if(session[:user_id].nil?)
      render layout: false
    else
      redirect_to select_univ_path
    end
  end
  
  #학교 선택 controller -> next selection2
  def selection 
    @select = User.group(:school)
    #@select = User.find_by_sql "SELECT id, school From Users group by school"
  end

  #보낼 사람 선택 controller -> next selection3
  def selection2
    @school = User.find(params[:id]).school
    @select = User.where(:school => @school).all
    @team = @select.group(:team)
    @new_post = Post.new
  end
  
  #메세지 입력받는 controller -> next sendsms
  def selection3
    @id = params[:id]
    @new_post = Post.new
  end
  
  #selection3 에서 입력받은 메세지를 보내는 controller
  def sendsms
    @post = Post.new(params.require(:post).permit(:context, :receiver_id))
    
    current_user = User.find(session[:user_id])
    
  #  @post.receiver_id = params[:id]
    @post.user_id = current_user.id
    @post.ischeck = 0
    
    if verify_recaptcha(:model => @post) && @post.save
      @temp = Bitly.client.shorten('http://share.likelion.net/sharing/reassure/' + @post.id.to_s)

      #current_user & sender = 요청한 사람
      #receiver = 요청받은 사람
      
      lms_user = '*****'
      lms_password = '*****'
      msg = @post.context + "\n번호공개의 동의하시면 다음 링크를 클릭해주세요  " + @temp.short_url
      title  = "멋쟁이 사자의 "  + current_user.name + "님이 보낸 문자입니다" ##문자 메시지
      
      h = Hash.new
      h["senderPhone"] = "*****"
      h["receivePhone"] = User.find(params[:id]).mobile
      
      hash_value = Digest::MD5.hexdigest(lms_user + lms_password + h["receivePhone"])
      h["hashValue"] = hash_value
      h["lmsContent"] = msg
      h["lmsID"] = lms_user
      h["lmsTitle"] = title
      
      client = Savon.client(wsdl: "http://lmsservice.tongkni.co.kr/lms.1/ServiceLMS.asmx?WSDL")
      res = client.call :send_lms, :message => h
      puts res.inspect
      flash.delete :recaptcha_error
      flash[:success] = "성공적으로 문자를 보냈습니다"
    else
      flash.delete :recaptcha_error
      flash[:error] = "recapcha 인증에 실패하였습니다"
      redirect_to :back
    end  
  end
  
  
  
  #로그인 controller 이쪽은 무시하셔도 됩니다.
  def confirm_id
    @user = User.where(:email => params[:user_id]).take
    if @user.nil?
      redirect_to :back
      flash[:error] = "잘못된 정보로 로그인했습니다"
    else
      password = BCrypt::Password.create(params[:user_password])
      salt = @user.password[0...29]
      
      @a = BCrypt::Engine.hash_secret(params[:user_password], salt)
      if (@user.password == @a)  
        redirect_to '/sharing/selection'
        session[:user_id] = @user.id
        flash[:success] = "로그인 하였습니다."
      else
        flash[:error] = "잘못된 정보로 로그인했습니다"
        redirect_to :back
      end      
    end
    
  end
  
  
  #로그 아웃 controller
  def logout
    reset_session
    redirect_to '/'
  end
  
private
  def check_session
    if(session[:user_id].nil?)
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
  
  def school_img(school)
    case school
    when "인하대학교"
      "inha"
    when "중앙대학교"
      "cau"
    when "충남대학교"
      "cnu"
    when "단국대학교"
      "dankook"
    when "동국대학교"
      "dongduk"
    when "덕성여자대학교"
      "duksung"
    when "동덕여자대학교"
      "duksung"  
    when "이화여자대학교"
      "ewha"
    when "유학생"
      "foreign"
    when "한동대학교"
      "handong"
    when "한양대학교"
      "hanyang"
    when "한국외국어대학교"
      "hufs"  
    when "전남대학교"
      "jnu"  
    when "한국과학기술원"
      "kaist"  
    when "강원대학교"
      "kangwon"  
    when "한국예술종합학교"
      "karts"  
    when "경희대학교"
      "khu"  
    when "경북대학교"
      "knu"  
    when "건국대학교"
      "konkuk"  
    when "국민대학교"
      "kookmin"  
    when "고려대학교"
      "korea"  
    when "평택대학교"
      "ptu"  
    when "부산대학교"
      "pusan"  
    when "서울과학기술대학교"
      "seoultech"  
    when "성균관대학교"
      "skku"  
    when "서울대학교"
      "snu"  
    when "서강대학교"
      "sogang"  
    when "숙명여자대학교"
      "sookmyung"  
    when "성신여자대학교"
      "sungshin"  
    when "서울여자대학교"
      "swu"  
    when "UNIST"
      "unist"  
    when "서울시립대학교"
      "uos"  
    when "원광대학교"
      "wku"  
    when "연세대학교"
      "yonsei"  
    when "영남대학교"
      "yungnam"  
    when "아주대학교"
      "ajou"
    else
      "admin"
    end
  end
end

app/helpers/capch_helper.rb
module CapchHelper
end

app/helpers/sharing_helper.rb
module SharingHelper
end

app/views/capch/index.html.erb
<h1>Capch#index</h1>
<p>Find me in app/views/capch/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YeonMo</title> <%# 이름바꿈.. %>
  <link rel="icon" type="image/png" href="/yeonmofinger.png" /> <%# 파비콘 설정 %>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%#= csrf_meta_tags %>
  <script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>  
   
</head>
<body>
  <nav class="navbar navbar-default" style = "background-color:rgba(255,255,255,0.2)">
    <div class="container">
      <div class = "row">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>            
        </div><!--navbar-header-->
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav nav-margin-left">
              <li><a href = "/sharing/selection" ><strong>UNIV</strong></a></li>
              <li><a href = "/sharing/mymessages" ><strong>MESSAGE</strong></a></li>
            </ul> 
            <ul class="nav navbar-nav pull-right nav-margin-right">
              <%unless session[:user_id].nil?%>
                <li><a href = "/sharing/logout"><strong>LOGOUT</strong></a></li>
             <%end %>
          </ul>
        </div><!--/.nav-collapse -->
     </div>
    </div><!--/.container -->
  </nav>
  <%= yield %>
</body>
</html>

app/views/sharing/_flash_message.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
    </div>
<% end %>

app/views/sharing/confirm.html.erb
<h1><%=@user%></h1>

app/views/sharing/confirm_sms.html.erb
<center><h1 style="color:white;">성공적으로 공유되었습니다.</h1></center>

app/views/sharing/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YeonMo</title> <%# 이름바꿈.. %>
  <link rel="icon" type="image/png" href="yeonmofinger.png" /> <%# 파비콘 설정 %>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%#= csrf_meta_tags %> 
</head>
<body>

<div class="container">

  <div class="col-xs-10 col-sm-10 col-md-4 col-md-offset-4 col-xs-8 col-xs-offset-2">

     <center><img src = "/yeonmo.png" class = "likelionface"/></center><%# 로고 얼굴 붙임 %>
        <%= render partial: "sharing/flash_message", flash: flash %>
    <div class = "login-title">
      <center>멋쟁이 사자처럼 3기 연락처 모음집</center><%# 소개 %>
    </div>
    <div class = "login-description">
      <center>* 클래스 라이언 아이디와 비밀번호로 로그인하세요 </center><%# 한class에 모음 %>
    </div>
      <form action="/sharing/confirm_id/" method = "POST">
        <div class="form-group">
          <center><input type="text" class="form-control" name="user_id" placeholder="Email"></center>
        </div>
        <div class="form-group">
          <center><input type="password" class="form-control" name="user_password" placeholder="Password"></center>
        </div>
        
        
        <div class="form-action">
          <center><input  type="submit" value="입장" class="btn btn-default btn-login"></center><%# 가운데 정렬. scss가서 참고하시길 %>
        </div>
      </form>
  </div>
</div>

</body>
</html>

app/views/sharing/mymessages.html.erb
<div class = "container">
  <div class= "row">  
    <div class="list-group">
      <table class = "table" style = "background-color:white">
        <thead>
          <th class = "text-center col-lg-1">상태</th>
          <th>내용</th>
          <th>받은 사람</th>
        </thead>
          <%@user.posts.each do |p| %>
            <tr>
            <td class = "text-center col-lg-1r">
                <%if p.ischeck == 1%>
                  <button class = "btn btn-danger  btn-sm">거절</button>
                <%elsif p.ischeck == 2%>
                  <button class = "btn btn-primary btn-sm">수락</button>
                <%else p.ischeck == 0%>
                  <button class = "btn btn-default btn-sm">대기</button>
                <%end%>
              </td>
              <td ><%=p.context[0...30] %></td>
              <td ><%=User.find(p.receiver_id).name%></td>
            </tr>
          <%end%>
      </table>
    </div>     

</div>

app/views/sharing/reassure.html.erb
<h1 style = "color:white">번호 공개의 동의하시면 밑의 버튼을 눌러주세요</h1>
<a href = "/sharing/confirm_sms/<%=@post.id%>" >
<button  class = "btn btn-primary btn-lg" name = "status"  onclick="javascript:var win = window.open('','_self', '');win.close(); ">동의합니다</button>            
</a>
<a href = "/sharing/reject_sms/<%=@post.id%>" >
<button   class = "btn btn-danger btn-lg"name = "status" onclick="javascript:var win = window.open('','_self', '');win.close(); ">거절합니다</button>            
</a>

app/views/sharing/reject_sms.html.erb
<h1>성공적으로 거절되었습니다.</h1>

app/views/sharing/selection.html.erb
<div class = "container" >
  <%= render partial: "sharing/flash_message", flash: flash %>
  <div class = "row">
    <%@select.each do |a|%>
      <a href="/sharing/selection2/<%=a.id%>" >
        <div class = "uni univ-img" >
          <div class = "uni-header text-center"><img src = "/univ/<%=school_img(a.school)%>.jpg"></div>
          <div class = "uni-footer text-center"><strong><%=a.school%></strong></div>
        </div></a>
    <%end%>
  </div>    
</div>
 

app/views/sharing/selection2.html.erb
<div class = "container">
  <%= render partial: "sharing/flash_message", flash: flash %>
  <div class= "row">  
    <div class = "col-lg-offset-4 col-lg-4 col-md-offset-4 col-md-4 ">
      <%@team.each do |t| %>
        <div class = "row">
          <div class = "text-center">
            <button class = "btn btn-pri" ><%=t.team%></button>
          </div>
          <%@select.each do |s| %>
            <%if t.team == s.team%>
              <div class = "col-lg-4 col-sm-4 col-xs-4">
                <div class = "row">
                <%if s.role == "USER"%>
                  <a  class="btn btn-default inform_stu text-center" data-toggle="modal" data-target="#myModal" data-user = "<%=s.id%>"><%=s.name%></a>    
                <%else%>
                  <a class="btn btn-default inform_leader text-center" data-toggle="modal" data-target="#myModal" data-user = "<%=s.id%>"><button class = "btn btn-default btn-xs btn-leader">L</button></br><%=s.name%></a>
                <%end%>
                </div>
              </div>
            <%end%>
          <%end%>
        </div>
      <%end%>  
    </div>
  </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">문자 내용을 입력해 주세요.</h4>
      </div>
      <div class="modal-body">
         <%= form_for @new_post, url: send_sms_path, method: "get" do |f| %> 
          <div class="form-group">
            <%=  f.text_area :context, class: 'form-control',  style: "width: 100%; height: 200px;"%>
          </div>
          <div class="form-group">
            <%= recaptcha_tags :ajax => "true" %> 
          </div>
          <div class="form-group">
            <%=  f.button :submit, class: 'btn  btn-lg btn-primary' %>
            <%=  f.hidden_field :receiver_id, class: 'btn  btn-lg btn-primary', value: "aaaa" %>          
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>


<script>
$('#myModal').on('show.bs.modal', function (event) {
   var button = $(event.relatedTarget);
   var recipient = button.data('user') // Extract info from data-* attributes
   $('#post_receiver_id').val(recipient);
   
});

</script>

app/views/sharing/selection3.html.erb
<div class = "container-fluid" >
  <div class = "row">
     <div class = "col-md-12 col-xs-12 ">       
           <div class = "col-md-4 col-md-offset-4">
            <p class ="">보내고 싶은 메시지를 작성하세요.<br>
             <% flash.each do |type, message| %>
<div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<%= message %>
</div>
<% end %>
             <%= form_for @new_post, url: send_sms_path(@id), method: "get" do |f| %> 
                <div class="form-group">
                  <%=  f.text_area :context, class: 'form-control', :size => "24x6" %>
                 </div>
                 <div class="form-group">
                  <%= recaptcha_tags :ajax => "true" %> 
                </div>                
                <div class="form-group">
                  <%=  f.button :submit, class: 'btn  btn-lg btn-primary' %>
                </div>    
            <%end%>
                        
              <br>
              <span style = "font-size :20px;color:rgba(255,255,255,0.8)">상대방이 동의하면 핸드폰으로 상대방의 번호가 전달됩니다.</span>
            </div>
         </div>
        </div>
    </div>

app/views/sharing/sendsms.html.erb
<h1>요청이 성공적으로 보내졌습니다.</h1>

app/views/sharing/signup.html.erb
<h1 id ="index_title">
    <strong><span style ="font-size:120px">S</span>haring<span style ="font-size:80px">N</span>umber</strong>
</h1>
<div class="jumbotron" style="background-color:rgba(255,255,255,0.2)">
    <div class = "container-fluid">
      <div class = "col-md-4 col-md-offset-4 col-xs-8 col-xs-offset-2">
            <p style ="color:white; font-family:BM-HANNAWeb">가입정보를 입력하세요</p>
            
            <form action ="/sharing/index">
                <p style ="color:white; font-family:BM-HANNAWeb">
                아이디 </p><input type = "text" name = "signup_id" placeholder="email-adress"><br>
    
                <p style ="color:white; font-family:BM-HANNAWeb">
                패스워드</p><input type = "password" name = "signup_pw">
               
                <input type="submit" value = "가입">
            </form>
        </div>
    </div>
</div>